name: Publicar Imagen Docker

on:
  push:
    branches: [master, dev]

jobs:
  build-and-push-to-ghcr:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.ref_name == 'master' && 'latest' || github.ref_name }}
      DOCKERFILE: ${{ github.ref_name == 'master' && 'Dockerfile' || 'Dockerfile.dev' }}
      BACKEND_URL: ${{ github.ref_name == 'master' && secrets.BACKEND_URL_PROD || secrets.BACKEND_URL_DEV }}

    permissions:
      contents: read
      packages: write # Permiso para publicar en GHCR

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Iniciar sesión en GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Token automático de GitHub

      - name: Construir y publicar la imagen (CD)
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: ghcr.io/ingsis-second-chance/printscript-ui:${{ env.IMAGE_TAG }}
          file: ./${{ env.DOCKERFILE }}
          build-args: |
            VITE_AUTH0_DOMAIN=${{ secrets.VITE_AUTH0_DOMAIN }}
            VITE_AUTH0_CLIENT_ID=${{ secrets.VITE_AUTH0_CLIENT_ID }}
            BACKEND_URL=${{ env.BACKEND_URL }}

  deploy-to-azure:
    runs-on: ubuntu-latest
    needs: build-and-push-to-ghcr

    env:
      SSH_KEY: ${{ github.ref_name == 'master' && secrets.SSH_KEY_PROD || secrets.SSH_KEY_DEV }}
      VM_IP: ${{ github.ref_name == 'master' && secrets.VM_PROD_IP || secrets.VM_DEV_IP }}
      DOCKER_COMPOSE_FILE: ${{ github.ref_name == 'master' && 'docker-compose.prod.yml' || 'docker-compose.dev.yml' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH client
        run: sudo apt-get install openssh-client -y

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0 # Evita exponer la clave privada en los logs
        with:
          ssh-private-key: ${{ env.SSH_KEY }}

      - name: Deploy to Azure VM
        run: |
          ssh -v -o StrictHostKeyChecking=no ingsis@${{ env.VM_IP }} << 'ENDSSH'
          cd infra
          docker compose -f ${{ env.DOCKER_COMPOSE_FILE }} down ui-service
          docker compose -f ${{ env.DOCKER_COMPOSE_FILE }} pull ui-service
          docker compose -f ${{ env.DOCKER_COMPOSE_FILE }} up -d ui-service
          ENDSSH